server:
  port: 5000
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${rds.hostname}:${rds.port}/${rds.db.name}?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  flyway:
    url: jdbc:postgresql://${rds.hostname}:${rds.port}/${rds.db.name}?useTimezone=true&serverTimezone=UTC
    schemas: public
    user: postgres
    password: postgres

