DROP TABLE IF EXISTS car;
CREATE TABLE IF NOT EXISTS car
(
    id NUMERIC(19) NOT NULL,
    make VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    license_plate VARCHAR(7) NOT NULL,
    manufacture_year INTEGER NULL,
    date_created TIMESTAMP NOT NULL,
    CONSTRAINT pk_car PRIMARY KEY (id)
);

DROP SEQUENCE IF EXISTS s_car;
CREATE SEQUENCE IF NOT EXISTS s_car
    CYCLE
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9999999999999
    CACHE 1;